---
title: "Beta Metrics Temporal"
author: Henry Paz
output: html_notebook
---

Beta metrics for Holstein and Jersey.

```{r, engine='bash'}
#create directory beta_metrics_holstein
mkdir beta_metrics_holstein

#calculate beta metrics
qiime diversity beta-phylogenetic \
  --i-table asv_holstein.qza \
  --i-phylogeny rooted_tree.qza \
  --p-metric weighted_unifrac \
  --o-distance-matrix beta_metrics_holstein/weighted_unifrac_distance_matrix.qza

qiime tools export \
  --input-path beta_metrics_holstein/weighted_unifrac_distance_matrix.qza \
  --output-path exported/holstein_weighted_unifrac_distance_matrix
  
#principal coordinate analysis
qiime diversity pcoa \
  --i-distance-matrix beta_metrics_holstein/weighted_unifrac_distance_matrix.qza \
  --o-pcoa beta_metrics_holstein/weighted_unifrac_pcoa_results.qza
  
qiime tools export \
  --input-path beta_metrics_holstein/weighted_unifrac_pcoa_results.qza \
  --output-path exported/holstein_weighted_unifrac_pcoa_results

#generate interactive ordination plot
qiime emperor plot \
--i-pcoa beta_metrics_holstein/weighted_unifrac_pcoa_results.qza \
--m-metadata-file metadata/rumen_metadata.txt \
--o-visualization visualizations/holstein_weighted_unifrac_emperor.qzv
#qiime tools view visualizations/holstein_weighted_unifrac_emperor.qzv

#compare beta diversity across time
qiime diversity beta-group-significance \
  --i-distance-matrix beta_metrics_holstein/weighted_unifrac_distance_matrix.qza \
  --m-metadata-file metadata/rumen_metadata.txt \
  --m-metadata-column time \
  --p-method permanova \
  --p-permutations 999 \
  --p-pairwise \
  --o-visualization visualizations/weighted_unifrac_holstein_time_significance.qzv 
#qiime tools view visualizations/weighted_unifrac_holstein_time_significance.qzv 

qiime tools export \
  --input-path visualizations/weighted_unifrac_holstein_time_significance.qzv \
  --output-path exported/weighted_unifrac_holstein_time_significance

#compare beta diversity across days
qiime diversity beta-group-significance \
  --i-distance-matrix beta_metrics_holstein/weighted_unifrac_distance_matrix.qza \
  --m-metadata-file metadata/rumen_metadata.txt \
  --m-metadata-column day \
  --p-method permanova \
  --p-permutations 999 \
  --p-pairwise \
  --o-visualization visualizations/weighted_unifrac_holstein_day_significance.qzv 
#qiime tools view visualizations/weighted_unifrac_holstein_day_significance.qzv 

qiime tools export \
  --input-path visualizations/weighted_unifrac_holstein_day_significance.qzv \
  --output-path exported/weighted_unifrac_holstein_day_significance
  
#create directory beta_metrics_jersey
mkdir beta_metrics_jersey

#calculate beta metrics
qiime diversity beta-phylogenetic \
  --i-table asv_jersey.qza \
  --i-phylogeny rooted_tree.qza \
  --p-metric weighted_unifrac \
  --o-distance-matrix beta_metrics_jersey/weighted_unifrac_distance_matrix.qza

qiime tools export \
  --input-path beta_metrics_jersey/weighted_unifrac_distance_matrix.qza \
  --output-path exported/jersey_weighted_unifrac_distance_matrix
  
#principal coordinate analysis
qiime diversity pcoa \
  --i-distance-matrix beta_metrics_jersey/weighted_unifrac_distance_matrix.qza \
  --o-pcoa beta_metrics_jersey/weighted_unifrac_pcoa_results.qza
  
qiime tools export \
  --input-path beta_metrics_jersey/weighted_unifrac_pcoa_results.qza \
  --output-path exported/jersey_weighted_unifrac_pcoa_results

#generate interactive ordination plot
qiime emperor plot \
--i-pcoa beta_metrics_jersey/weighted_unifrac_pcoa_results.qza \
--m-metadata-file metadata/rumen_metadata.txt \
--o-visualization visualizations/jersey_weighted_unifrac_emperor.qzv
#qiime tools view visualizations/jersey_weighted_unifrac_emperor.qzv

#compare beta diversity across time
qiime diversity beta-group-significance \
  --i-distance-matrix beta_metrics_jersey/weighted_unifrac_distance_matrix.qza \
  --m-metadata-file metadata/rumen_metadata.txt \
  --m-metadata-column time \
  --p-method permanova \
  --p-permutations 999 \
  --p-pairwise \
  --o-visualization visualizations/weighted_unifrac_jersey_time_significance.qzv 
#qiime tools view visualizations/weighted_unifrac_jersey_time_significance.qzv 

qiime tools export \
  --input-path visualizations/weighted_unifrac_jersey_time_significance.qzv \
  --output-path exported/weighted_unifrac_jersey_time_significance

#compare beta diversity across days
qiime diversity beta-group-significance \
  --i-distance-matrix beta_metrics_jersey/weighted_unifrac_distance_matrix.qza \
  --m-metadata-file metadata/rumen_metadata.txt \
  --m-metadata-column day \
  --p-method permanova \
  --p-permutations 999 \
  --p-pairwise \
  --o-visualization visualizations/weighted_unifrac_jersey_day_significance.qzv 
#qiime tools view visualizations/weighted_unifrac_jersey_day_significance.qzv 

qiime tools export \
  --input-path visualizations/weighted_unifrac_jersey_day_significance.qzv \
  --output-path exported/weighted_unifrac_jersey_day_significance
```

Generate distance PCoA plots.

```{r}
#load libraries
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(vegan)

#PERMANOVA and PCoA
#create holstein dataset
pcoa_holstein <- read_tsv("exported/holstein_weighted_unifrac_pcoa_results/ordination.txt", col_names = c("SampleID", "PC1", "PC2"), skip=9) %>%
  slice(1:75) # select rows 1 to 75

#create time dataset
ids_time <-  read_tsv("metadata/rumen_metadata.txt") %>% 
  select("#SampleID", breed, time) %>% 
  rename(SampleID="#SampleID", Breed=breed, Time=time) %>% 
  slice(2:153) %>% 
  filter(Breed=="Holstein") %>% 
  na.omit() 

#join pcoa_holstein and ids_time datasets
pcoa_time_holstein <- left_join(pcoa_holstein, ids_time, by = "SampleID") %>% 
  select(SampleID, Time, PC1, PC2) #reorder columns

#PERMANOVA
#weighted unifrac distance matrix data
weighted_unifrac_holstein <- read_tsv("exported/holstein_weighted_unifrac_distance_matrix/distance-matrix.tsv")
weighted_unifrac_holstein <- as.data.frame(weighted_unifrac_holstein)

#Match sampleid order of matrix
ids_time = ids_time[match(weighted_unifrac_holstein$X1, ids_time$SampleID), ]

#generate matrix
row.names(weighted_unifrac_holstein) <- weighted_unifrac_holstein$X1
weighted_unifrac_holstein <- weighted_unifrac_holstein[, -1]
weighted_unifrac_holstein <- as.dist(weighted_unifrac_holstein)

#PERMANOVA
adonis(weighted_unifrac_holstein ~ Time, permutations=999, data=ids_time)

#PCoA plot
holstein_pcoa_time_plot <- ggplot(pcoa_time_holstein, aes(x=PC1,y=PC2,shape=Time,color=Time)) + annotate(geom="text", x=-0.15, y=0.11, size=4, fontface="bold", color="#800000", label="PERMANOVA, P = 0.57") + geom_point(size=3) + ggtitle("Holstein") + labs(x="PC1 (35.4%)", y="PC2 (12.4%)",shape="Time",color="Time") + theme(plot.title=element_text(color="black", size=16, face="bold", hjust=0.5), axis.line=element_line(color="black", size=1), axis.ticks=element_line(color="black"), axis.text=element_text(color="black", size=12, face="bold"), axis.title=element_text(color="black", size=14, face="bold"), legend.title=element_text(color="black",size=10,face="bold"), legend.text=element_text(color="black",size=9,face="bold")) + scale_color_manual(name="Time (h)", values=c("Black","Red","Blue","Green","Purple"), limits=c("0","6","12","18","24")) + scale_shape_manual(name="Time (h)", values=c(20,18,15,8,17), limits=c("0","6","12","18","24"))

#create day dataset
ids_day <-  read_tsv("metadata/rumen_metadata.txt") %>% 
  select("#SampleID", breed, day) %>% 
  rename(SampleID="#SampleID", Breed=breed, Day=day) %>% 
  slice(2:153) %>% 
  filter(Breed=="Holstein") %>% 
  na.omit() 

#join pcoa_holstein and ids_day datasets
pcoa_day_holstein <- left_join(pcoa_holstein, ids_day, by = "SampleID") %>% 
  select(SampleID, Day, PC1, PC2) #reorder columns

#PERMANOVA
#weighted unifrac distance matrix data
weighted_unifrac_holstein <- read_tsv("exported/holstein_weighted_unifrac_distance_matrix/distance-matrix.tsv")
weighted_unifrac_holstein <- as.data.frame(weighted_unifrac_holstein)

#Match sampleid order of matrix
ids_day = ids_day[match(weighted_unifrac_holstein$X1, ids_day$SampleID), ]

#generate matrix
row.names(weighted_unifrac_holstein) <- weighted_unifrac_holstein$X1
weighted_unifrac_holstein <- weighted_unifrac_holstein[, -1]
weighted_unifrac_holstein <- as.dist(weighted_unifrac_holstein)

#PERMANOVA
adonis(weighted_unifrac_holstein ~ Day, permutations=999, data=ids_day)

#PCoA plot
holstein_pcoa_day_plot <- ggplot(pcoa_day_holstein, aes(x=PC1,y=PC2,shape=Day,color=Day)) + labs(x="PC1 (35.4%)", y="PC2 (12.4%)",shape="Day",color="Day") + annotate(geom="text", x=-0.18, y=0.15, size=4, fontface="bold", color="#800000", label="PERMANOVA, P < 0.01") + geom_point(size=3) + ggtitle("Holstein") + theme(plot.title=element_text(color="black", size=16, face="bold", hjust=0.5), axis.line=element_line(color="black", size=1), axis.ticks=element_line(color="black"), axis.text=element_text(color="black", size=12, face="bold"), axis.title=element_text(color="black", size=14, face="bold"), legend.title=element_text(color="black",size=10,face="bold"), legend.text=element_text(color="black",size=9,face="bold")) + stat_ellipse(aes(fill=Day), alpha=0.2, type="t", level=0.95, size=0.5, geom="polygon", show.legend=F) + scale_shape_manual(name="Day", values=c(20,18,15)) + scale_color_manual(name="Day", values=c("Black","Red","Blue")) + scale_fill_manual(values=c("Black","Red","Blue"))
  
#create jersey dataset
pcoa_jersey <- read_tsv("exported/jersey_weighted_unifrac_pcoa_results/ordination.txt", col_names = c("SampleID", "PC1", "PC2"), skip=9) %>%
  slice(1:75) # select rows 1 to 75

#create time dataset
ids_time <-  read_tsv("metadata/rumen_metadata.txt") %>% 
  select("#SampleID", breed, time) %>% 
  rename(SampleID="#SampleID", Breed=breed, Time=time) %>% 
  slice(2:153) %>% 
  filter(Breed=="Jersey") %>% 
  na.omit() 

#join pcoa_jersey and ids_time datasets
pcoa_time_jersey <- left_join(pcoa_jersey, ids_time, by = "SampleID") %>% 
  select(SampleID, Time, PC1, PC2) #reorder columns

#PERMANOVA
#weighted unifrac distance matrix data
weighted_unifrac_jersey <- read_tsv("exported/jersey_weighted_unifrac_distance_matrix/distance-matrix.tsv")
weighted_unifrac_jersey <- as.data.frame(weighted_unifrac_jersey)

#Match sampleid order of matrix
ids_time = ids_time[match(weighted_unifrac_jersey$X1, ids_time$SampleID), ]

#generate matrix
row.names(weighted_unifrac_jersey) <- weighted_unifrac_jersey$X1
weighted_unifrac_jersey <- weighted_unifrac_jersey[, -1]
weighted_unifrac_jersey <- as.dist(weighted_unifrac_jersey)

#PERMANOVA
adonis(weighted_unifrac_jersey ~ Time, permutations=999, data=ids_time)

#PCoA plot
jersey_pcoa_time_plot <- ggplot(pcoa_time_jersey, aes(x=PC1,y=PC2,shape=Time,color=Time)) + annotate(geom="text", x=-0.09, y=0.12, size=4, fontface="bold", color="#800000", label="PERMANOVA, P = 0.54") + geom_point(size=3) + ggtitle("Jersey") + labs(x="PC1 (37.0%)", y="PC2 (12.3%)",shape="Time",color="Time") + theme(plot.title=element_text(color="black", size=16, face="bold", hjust=0.5), axis.line=element_line(color="black", size=1), axis.ticks=element_line(color="black"), axis.text=element_text(color="black", size=12, face="bold"), axis.title=element_text(color="black", size=14, face="bold"), legend.title=element_text(color="black",size=10,face="bold"), legend.text=element_text(color="black",size=9,face="bold")) + scale_color_manual(name="Time (h)", values=c("Black","Red","Blue","Green","Purple"), limits=c("0","6","12","18","24")) + scale_shape_manual(name="Time (h)", values=c(20,18,15,8,17), limits=c("0","6","12","18","24"))

#create day dataset
ids_day <-  read_tsv("metadata/rumen_metadata.txt") %>% 
  select("#SampleID", breed, day) %>% 
  rename(SampleID="#SampleID", Breed=breed, Day=day) %>% 
  slice(2:153) %>% 
  filter(Breed=="Jersey") %>% 
  na.omit() 

#join pcoa_jersey and ids_day datasets
pcoa_day_jersey <- left_join(pcoa_jersey, ids_day, by = "SampleID") %>% 
  select(SampleID, Day, PC1, PC2) #reorder columns

#PERMANOVA
#weighted unifrac distance matrix data
weighted_unifrac_jersey <- read_tsv("exported/jersey_weighted_unifrac_distance_matrix/distance-matrix.tsv")
weighted_unifrac_jersey <- as.data.frame(weighted_unifrac_jersey)

#Match sampleid order of matrix
ids_day = ids_day[match(weighted_unifrac_jersey$X1, ids_day$SampleID), ]

#generate matrix
row.names(weighted_unifrac_jersey) <- weighted_unifrac_jersey$X1
weighted_unifrac_jersey <- weighted_unifrac_jersey[, -1]
weighted_unifrac_jersey <- as.dist(weighted_unifrac_jersey)

#PERMANOVA
adonis(weighted_unifrac_jersey ~ Day, permutations=999, data=ids_day)

#PCoA plot
jersey_pcoa_day_plot <- ggplot(pcoa_day_jersey, aes(x=PC1,y=PC2,shape=Day,color=Day)) + annotate(geom="text", x=-0.11, y=0.15, size=4, fontface="bold", color="#800000", label="PERMANOVA, P < 0.01") + labs(x="PC1 (37.0%)", y="PC2 (12.3%)",shape="Day",color="Day")  + geom_point(size=3) + ggtitle("Jersey") + theme(plot.title=element_text(color="black", size=16, face="bold", hjust=0.5), axis.line=element_line(color="black", size=1), axis.ticks=element_line(color="black"), axis.text=element_text(color="black", size=12, face="bold"), axis.title=element_text(color="black", size=14, face="bold"), legend.title=element_text(color="black",size=10,face="bold"), legend.text=element_text(color="black",size=9,face="bold")) + stat_ellipse(aes(fill=Day), alpha=0.2, type="t", level=0.95, size=0.5, geom="polygon", show.legend=F) + scale_shape_manual(name="Day", values=c(20,18,15)) + scale_color_manual(name="Day", values=c("Black","Red","Blue")) + scale_fill_manual(values=c("Black","Red","Blue"))

#combine plots
pcoa_plots <- ggarrange(holstein_pcoa_time_plot,jersey_pcoa_time_plot,
                        holstein_pcoa_day_plot, jersey_pcoa_day_plot,
                        labels = c("A","B", "C", "D"),
                        ncol = 2, nrow = 2)

#generate figure
ggexport(pcoa_plots, filename="figures/Figure4.pdf", height=8, width=12)

jpeg("figures/Figure4.jpg", units="in", height=8, width=12, res=300)
pcoa_plots
dev.off()
```
